## =====================================================================
## Factory Ops Backend - PROD Profile
## =====================================================================

quarkus.log.console.json=true
quarkus.log.level=INFO

# Prod: do not seed data
factory.ops.seed.enabled=false

# Prod: use real NATS
nats.enabled=true

# Prod: disable swagger (enable via env var if needed)
quarkus.swagger-ui.always-include=${SWAGGER_ENABLED:false}

# Prod: MongoDB DevServices disabled
quarkus.mongodb.devservices.enabled=false

# JWT keys from env in prod
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION}
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION}
